name: apply
on:
  pull_request:
    branches: [prod]
    types: [closed]
jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform Apply
        id: apply
        working-directory: ./prod
        run: |
          terraform init
          terraform apply -auto-approve
